// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPpg8IhrQNCTvENaDZ-jkDbIblf1VbmIA',
    appId: '1:346391310222:web:4c83077f9356baa9c73edf',
    messagingSenderId: '346391310222',
    projectId: 'booking-finland-washing-machin',
    authDomain: 'booking-finland-washing-machin.firebaseapp.com',
    storageBucket: 'booking-finland-washing-machin.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcoLGteuahzrY3_7CM_uNgi7o6cxHibds',
    appId: '1:346391310222:android:2ab9497e94b271f6c73edf',
    messagingSenderId: '346391310222',
    projectId: 'booking-finland-washing-machin',
    storageBucket: 'booking-finland-washing-machin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3hutXPFQytqjaZYXPIrJuqd7bY2ZOz64',
    appId: '1:346391310222:ios:e7ef23ee2541a1d8c73edf',
    messagingSenderId: '346391310222',
    projectId: 'booking-finland-washing-machin',
    storageBucket: 'booking-finland-washing-machin.appspot.com',
    iosBundleId: 'com.example.bookingFinlandWashingMachine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3hutXPFQytqjaZYXPIrJuqd7bY2ZOz64',
    appId: '1:346391310222:ios:a59d2f95dabffd9ac73edf',
    messagingSenderId: '346391310222',
    projectId: 'booking-finland-washing-machin',
    storageBucket: 'booking-finland-washing-machin.appspot.com',
    iosBundleId: 'com.example.bookingFinlandWashingMachine.RunnerTests',
  );
}
